# Source site files.
for f in `find ~/.rpt_profile/etc/sites -type f`; do 
    source $f
done

source ~/.rpt_profile/etc/bash_aliases
source ~/.rpt_profile/etc/exports
source ~/.rpt_profile/etc/inputrc


# Use bash completion on Darwin. Should already be installed on Linux.
if [[ `uname` == 'Darwin' ]]; then
    if [[ -f `brew --prefix`/etc/bash_completion ]]; then
        source `brew --prefix`/etc/bash_completion
    else
        echo "bash-completion is not installed!"
    fi
fi
