syn on
colorscheme default
" :W also saves.
command! W w

set autoread
set encoding=utf-8
set hlsearch
set ignorecase
set smartcase
set incsearch
" Show lines to left of buffer.
set number  
" Show line and column in status area.
set ruler 
set showcmd


"""
" Tab-related settings.
"""
"set autoindent
" Smart indenting behavior.
filetype indent on
" Soft tab.
set expandtab 
set showtabline=4
set softtabstop=4
" Shift indents 4 spaces.
set sw=4
set ts=4

set autoread

set wildmode=longest,list,full
set wildmenu

" We're running vim, not vi.
set nocompatible 
" Enable filetype detection.
filetype on 
" Enable filetype-specific indenting.
filetype indent on 
" Enable filetype-specific plugins.
filetype plugin on 

" No more shift!
nore ; :

" Consider '_' a word separator.
set iskeyword-=_


"""
" Filetype-specific stuff.
"""

" Clojure.
let vimclojure#HighlightBuiltins = 1
let vimclojure#ParenRainbow = 1
