syn on
colorscheme default
" :W also saves.
command! W w

set autoindent
set autoread
set encoding=utf-8
" Soft tab.
set expandtab 
set hlsearch
set ignorecase
set smartcase
set incsearch
" Show lines to left of buffer.
set number  
" Show line and column in status area.
set ruler 
set showcmd

" Tab-related settings.
set showtabline=4
set smartindent
set softtabstop=4
set sw=4
set ts=4

set autoread

set wildmode=longest,list,full
set wildmenu

" We're running Vim, not Vi!
set nocompatible 
" Enable filetype detection.
filetype on 
" Enable filetype-specific indenting.
filetype indent on 
" Enable filetype-specific plugins.
filetype plugin on 
" No more shift!
nore ; :
" Consider _ to be a word separator.
set iskeyword-=_


